name: Container build and push

on:
  schedule:
    - cron: '25 23 */7 * *'
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # git clone repo to vm
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set build date
        id: set-date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set up BuildKit Docker container builder to be able to build
      - name: Set up 
        uses: docker/setup-buildx-action@v3
        # with:
        #   platforms: linux/amd64

      # Login against a Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # platforms: linux/amd64
          provenance: false
      
      - name: delete untagged containers
        uses: actions/delete-package-versions@v4
        with: 
          package-name: 'python-ml-container'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'
  
  # clean-ghcr:
  #   name: Delete old images
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Delete old images
  #       uses: actions/delete-package-versions@v4
  #       with: 
  #         package-name: 'python-ml-container'
  #         package-type: 'container'
  #         min-versions-to-keep: 5
